### ISSUE TITLE
404 trying to download models

### ISSUE THREAD

**Issue by dheera** [caffe2/models#11]
![2017-09-03 21-43-02](https://user-images.githubusercontent.com/1786477/30006809-324545ae-90b6-11e7-9c2c-6d6263389f88.png)

**Comment by dheera** [comment]
Never mind, fixed by reinstalling caffe2 to latest version. It would be helpful if instead of saying "404: Not found" it said something along the lines of:
  `Your caffe2 installation is out of date. Would you like to upgrade from version 0.0.1 to 0.0.2 [y/n]?`
or something of that sort.

**Comment by orionr** [comment]
Thanks @dheera - happy to hear an update worked. Closing.
