### ISSUE TITLE
SSD and Faster RCNN

### ISSUE THREAD

**Issue by RcRonco** [caffe2/models#12]
It's planned to add Faster RCNN and SSD (VGG/Resnet) models trained on MSCOCO?

**Comment by orionr** [comment]
Hi @RcRonco - there's a **great** set of models trained on COCO (including Faster R-CNN) by the original authors over at Detectron. These all run on Caffe2:

https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md

Please feel free to check those out and thanks!

**Comment by orionr** [comment]
Also, pre-trained VGG and ResNet models will be added to the Caffe2 model zoo shortly.

**Comment by chandanv2** [comment]
@orionr Faster-RCNN for VGG16 is not available for Caffe2 and to convert Caffe implementation of VGG16 to Caffe2 model, the caffe_translate.py throws an error stating:
google.protobuf.text_format.ParseError: 483:3 : Message type "caffe.LayerParameter" has no field named "roi_pooling_param".
Do you know any other way to realise VGG16 faster-rcnn models in Caffe2?
I can go for ResNet variants given by Detectron but I am looking for something which takes lesser time for inference like VGG16 and MobileNet. Please share if you have any information about them. 
Thank You :)

**Comment by orionr** [comment]
HI @chandanv2. At this point Detectron models are your best bet, but if you want to try vgg16 or vgg19 we do have those in the model zoo. You'll likely need to retrain the models, so you should install the Detectron code base and see if you can replace the ResNet trunk with a VGG variant over there. Hope that helps.

**Comment by rohitbhio** [comment]
@chandanv2 : Were you able to get VGG16 model compatible with detectron?

**Comment by chandanv2** [comment]
@rohitbhio Hey I didn't try that out Rohit. Sorry for the late reply.
