### ISSUE TITLE
Retrain models

### ISSUE THREAD

**Issue by CriCL** [caffe2/models#17]
Hi all

It's possible to retrain (also known as Transfer Learning) models like AlexNet?

Regards

**Comment by Maratyszcza** [comment]
The AlexNet model in this repo was converted from the original Caffe, and would require some work to train it in Caffe2. @orionr may have a native Caffe2 version.

**Comment by orionr** [comment]
Nothing available yet, but transfer learning (and pre-training) is definitely something we want to support and ultimately we're going to provide training scripts for a number of models. Stay tuned!

**Comment by CriCL** [comment]
Thanks for answering,

Regards

**Comment by orionr** [comment]
Also linking to the issue over on Caffe2 proper

https://github.com/caffe2/caffe2/issues/1850
