### ISSUE TITLE
Git LFS prevents prototxt preview in GitHub

### ISSUE THREAD

**Issue by huyouare** [caffe2/models#2]
Is it necessary to track all files (including small .prototxt files) with Git LFS? It prevents the preview in GitHub. 

![image](https://cloud.githubusercontent.com/assets/3528340/25159399/8d364f4e-247d-11e7-8234-6f63222a46dc.png)

**Comment by RSly** [comment]
it would be nice to have the previews!

**Comment by orionr** [comment]
Unfortunately the prototxt could be large, so we're going to keep using LFS for now, but it's a good comment. Thank you! As a workaround, you can always download with "View Raw".
