### ISSUE TITLE
Timeline for raw caffe2 c++ to support FPN

### ISSUE THREAD

**Issue by ChengshuLi** [caffe2/models#29]
Hi,

I would love to use e2e_faster_rcnn_R-50-FPN_1/2x for inference in caffe2 c++. I know that currently FPN is not yet supported. Do you guys have a timeline for when it would be supported?

Thanks a lot!

**Comment by orionr** [comment]
Hi @ChengshuLi. We are working on it so stay tuned! More work is still needed, but part of it is at https://github.com/caffe2/caffe2/pull/2254
