### ISSUE TITLE
Why was terminal eliminted?

### ISSUE THREAD

**Issue by neftaliw** [caffe2/models#3]
I liked how in Caffe I could easily train a model using the terminal, I don't see that in Caffe 2, nor a short example on how to do it on Python.

**Comment by harouwu** [comment]
You can write a python script like our python notebook tutorial. Then you can always run 
```python <your script.py>```

**Comment by neftaliw** [comment]
Sure, that has been available since Caffe, but now I have to write a long model specific script whereas before I just needed one terminal command to train. Caffe is a standalone framework with a Python interface, I feel Caffe2 is just a python library. You guys removed a lot of the functionality and user friendliness that Caffe had.

On Apr 24, 2017 10:38 PM, harouwu <notifications@github.com> wrote:

You can write a python script like our python notebook tutorial. Then you can always run
python <your script.py>

**Comment by orionr** [comment]
Hi @neftaliw. I think this is answered. Thank you.
