### ISSUE TITLE
Could not download model

### ISSUE THREAD

**Issue by hitspring2015** [caffe2/models#4]
when I run the shell
python -m caffe2.python.models.download -i squeezenet

it appear the error
 Downloading from https://s3.amazonaws.com/caffe2/models/squeezenet/predict_net.pb
Abort: Could not download model. [URL Error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590).
Cleaning up...

**Comment by aaronmarkham** [comment]
Hi, this sounds like an SSL cert error on your PC rather than an issue with the model downloader module. Can you curl or wget the file? I see some helpful threads regarding fixing CERTIFICATE_VERIFY_FAILED generally so I'd take a look at that. Please let me know if you can share a solution.

**Comment by hitspring2015** [comment]
ok ! The problem has been solved! the solution can reference the [PEP-0476](https://www.python.org/dev/peps/pep-0476/#trust-database)
the detail is 
```
cd ~/caffe2/build/caffe2/python/models
sudo gedit download.py
```

then add the opt

```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```
and then  I can download the models use the command
python download -i squeezenet

**Comment by hitspring2015** [comment]
the last command is 
`python download.py -i [modelname]`
