### ISSUE TITLE
how to run on gpu mode?

### ISSUE THREAD

**Issue by KeyKy** [caffe2/models#5]
I run this follow code with alexnet
p = workspace.Predictor(init_net, predict_net)
results = p.run([img])

It seem like the caffe2 run on cpu because I can not find the PID on nvidia-smi. I have already compile caffe2 in gpu mode.

**Comment by orionr** [comment]
@KeyKy looks like you might have found a fix over on the Caffe2 post? I'll close this one, since there's way more activity over there. Thanks.
