### ISSUE TITLE
squeezeNet is translated from v1.0 or v1.1 ?

### ISSUE THREAD

**Issue by KleinYuan** [caffe2/models#7]
Original [issue](https://github.com/KleinYuan/Caffe2-iOS/issues/8)

So, kinda curious what's the version of the squeezeNet in this repo.

**Comment by StanislawAntol** [comment]
I opened up `models/squeezenet/predict_net.pb` and it looks like it is a v1.1 (e.g., it has a pool3 layer instead of pool4).

**Comment by FullZing** [comment]
I have the same question.
