### ISSUE TITLE
Enforce fail, ParseProtobufFromLargeString

### ISSUE THREAD

**Issue by m00nkeh** [caffe2/models#9]
I'm trying to run the Ipython Notebook Load Pretrained Models tutorial using Squeezenet, but it's failing at `p = workspace.Predictor(init_net, predict_net)` with the error `RuntimeError: [enforce fail at E:\caffe2\caffe2\python\pybind_state.cc:553] ParseProtobufFromLargeString(predict_net, &predict_net_).`

I'm a little confused about the files I'm meant to be using here: the two mentioned in the tutorial and that are downloaded from an AWS address are init_net.pb and predict_net.pb, while on the github there's a file called exec_net.pb and no init_net.pb. init_net/exec_net also seem to be in a totally different format to predict_net.

There seems to be an empty line at the top of predict_net.pb, and removing it changes the error to `RuntimeError: [enforce fail at E:\caffe2\caffe2\core\operator.cc:110] op. Cannot create operator of type '' on the device 'CPU'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: output: "conv1_w" `

Is there an error in the file?

**Comment by m00nkeh** [comment]
The same error occurs with the googlenet model, so it's not specific to squeezenet.

**Comment by m00nkeh** [comment]
I finally worked it out: the lines `with open(INIT_NET) as f:` and `with open(PREDICT_NET) as f:` need to be changed to `with open(INIT_NET, 'rb') as f:` and `with open(PREDICT_NET, 'rb') as f:`.

**Comment by bei91** [comment]
I also have the same problem, but in your way, it failed. The same error occurs.

**Comment by bei91** [comment]
I also have the same problem, but in the above solution, it failed. The same error occurs.
RuntimeError: [enforce fail at pybind_state.cc:554] ParseProtobufFromLargeString(predict_net, &predict_net_).

**Comment by bei91** [comment]
I finally worked it out:
Using the following command to generate the two files.
python -m caffe2.python.models.download -i squeezenet

**Comment by PhilBotSeesU** [comment]
I'm getting this issue as well. But now when I run the python -m caffe2.python.models.download -i squeezenet it throws the following. Any help would be appreciated. Everything out there seems for something else. 

Downloading from https://s3.amazonaws.com/caffe2/models/squeezenet/predict_net.pb
Abort: Could not download model. [URL Error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590).

**Comment by hfutzxy** [comment]
The same error occurs when i use the command:python -m caffe2.python.models.download -i squeezenet.

Abort: Could not download model. [URL Error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590).

**Comment by ugionet** [comment]
@m00nkeh 
Your solution is the only solution that worked for me  !! Thank you so much, i was struggling with this issue for so long.  Well done !! 
By the way i am running from Windows platform with Cuda 8, Cudnn 5.1 and  Opencv3.2. 
Thanks again .

**Comment by alexge233** [comment]
since I have run into the same issue, @m00nkeh which file did you edit?

**Comment by m00nkeh** [comment]
The lines `with open(INIT_NET) as f:` and `with open(PREDICT_NET) as f:` that need to be changed are in the iPython notebook file Loading_Pretrained_Models.ipynb.

**Comment by orionr** [comment]
Moving issue to the new tutorials repo. Thank you!

**Comment by youngxiao** [comment]
@m00nkeh I git clone all the models from model zoo to the folder ~/caffe2/python/models. I'm trying to run the Ipython Notebook Load Pretrained Models tutorial using Squeezenet, but it's failing at p = workspace.Predictor(init_net, predict_net) with the error RuntimeError: [enforce fail at E:\caffe2\caffe2\python\pybind_state.cc:553] ParseProtobufFromLargeString(predict_net, &predict_net_).  I changed the lines with open(INIT_NET) as f: and with open(PREDICT_NET) as f:  to with open(INIT_NET, 'rb') as f: and with open(PREDICT_NET, 'rb') as f: in the iPython notebook file Loading_Pretrained_Models.ipynb. But it not work.

**Comment by orionr** [comment]
@youngxiao what's the error you are seeing after you've made the `open` changes?

**Comment by youngxiao** [comment]
@orionr After I made the open changes. Still the same issue:
`RuntimeError: [enforce fail at E:\caffe2\caffe2\python\pybind_state.cc:553] ParseProtobufFromLargeString(predict_net, &predict_net_).`

**Comment by orionr** [comment]
@youngxiao is it possible that you don't have Git LFS installed? If you're pulling the models from the GitHub repository (versus the download script, which pulls from Amazon S3) you'll need to have Git LFS installed:

https://git-lfs.github.com/

You'll also likely need to pull the files again afterwards like

https://github.com/git-lfs/git-lfs/issues/325

Note that they are pretty large, so you might want to just download them individually like

```
python -m caffe2.python.models.download -i squeezenet
```
If that's not the issue I'll see if I can help debugging.

**Comment by shawnwinder** [comment]
I just load the 'init_net.pb' as unit test, then it throws error like this:

> [libprotobuf ERROR /home/zhibin/qzhong/thirdparty-source/protobuf-3.5.2/src/google/protobuf/io/coded_stream.cc:193] A protocol message was rejected because it was too big (more than 1073741824 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
> Original python traceback for operator -671088312 in network `` in exception above (most recent call last):
so, in my case there is a very large object in the .pb file has , which causing the error.
